# Extensión de visualcode. Podríamos haber usado Postman, insomia...
###
POST  http://localhost:3000/api/employees
Content-Type: application/json

{
    "name": "Tony McMircha",
    "position": "Sr. Sr. Developer",
    "office":"EEUU",
    "salary": "9000000"
}
###
GET  http://localhost:3000/api/employees/

###
GET  http://localhost:3000/api/employees/61358e221dbd6429e483ae27


###
DELETE http://localhost:3000/api/employees/6112ec8430ce0e22c86bda96

###
PUT http://localhost:3000/api/employees/61358e221dbd6429e483ae27
Content-Type: application/json

{
    "name": "Tonii Stark"
}

# -----------------CONTACTO-------------------
###
POST  http://localhost:3000/api/contacto
Content-Type: application/json

{
    "nombre":"Juana De Arco",
    "email": "crazydev@gmail.com",
    "edad":"270",
    "pais": "Norway",
    "comentario":"Hola quiero mas info!+5493454093473"
}
###
GET  http://localhost:3000/api/contacto

###
